services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file:
      - ./apps/api/.env
    ports:
      - "4000:4000"
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    env_file:
      - ./apps/web/.env.local
    ports:
      - "3000:3000"
  db:
    image: postgres:16
    container_name: terracota_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
